### ISSUE TITLE
Not working for me.

### ISSUE THREAD

**Issue by linkurzweg** [simonmeusel/hyperfull#2]
I installed the plugin, but it just does nothing. It's always starting in windowed mode.
I am using MacOS Sierra and hyper v.0.8.3

**Comment by qmnl** [comment]
Earlier hyper always started in windowed mode with lets say 400 \* 600 pixels. So I build this plugin to start it in windowed, but stretching the whole screen. Now hyper does this by default so I changed this plugin to start hyper in fullscreen mode :)

**Should be working by version 2.0, just try it again.**

**Comment by fyodoriv** [comment]
Doesn't work for me either. I expect it to have Hyper opened fullscreen by default.
I have added the plugin with 
`fisher simonmeusel/hyperfull`
and added a plugin `'hyperfull'` to the `plugins` section and restarted Hyper. It opened stretching the whole screen, but not full screen.
Mac

**Comment by qmnl** [comment]
See issue #3

**Comment by qmnl** [comment]
Use hyperfullscreen instead, see the readme
